#! /usr/bin/env python3

import sys

import tvfeed


def err (*msg):
    print('error:', *msg, file=sys.stderr)
    sys.exit(2)


if len(sys.argv) < 2:
    err('expected COMMAND argument')
command = sys.argv[1]
if command not in tvfeed.commands:
    err('unknown COMMAND:', command)
tvfeed.commands[command].run()
